In [1]:
import nltk
import pandas as pd
import numpy as np

In [2]:
message = pd.read_csv('SMSSpamCollection', sep='\t',names=['label','message'],encoding="latin1")

In [3]:
message

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [4]:
# binary classification (spam,ham)

In [5]:
# punctuation
import string
mess = 'Sample @message ! Notice: it has punctuations.'

In [6]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [7]:
import re
re.sub(r'[@!:]',' ',mess)

'Sample  message   Notice  it has punctuations.'

In [8]:
mess

'Sample @message ! Notice: it has punctuations.'

In [9]:
nopunc = [c for c in mess if c not in string.punctuation]

In [10]:
nopunc

['S',
 'a',
 'm',
 'p',
 'l',
 'e',
 ' ',
 'm',
 'e',
 's',
 's',
 'a',
 'g',
 'e',
 ' ',
 ' ',
 'N',
 'o',
 't',
 'i',
 'c',
 'e',
 ' ',
 'i',
 't',
 ' ',
 'h',
 'a',
 's',
 ' ',
 'p',
 'u',
 'n',
 'c',
 't',
 'u',
 'a',
 't',
 'i',
 'o',
 'n',
 's']

In [11]:
nopunc = ''.join(nopunc)

In [12]:
nopunc

'Sample message  Notice it has punctuations'

In [13]:
from nltk.corpus import stopwords

In [14]:
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [15]:
nopunc.split(' ')

['Sample', 'message', '', 'Notice', 'it', 'has', 'punctuations']

In [16]:
clean_mess = [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]

In [17]:
clean_mess

['Sample', 'message', 'Notice', 'punctuations']

In [18]:
final = ' '.join(clean_mess)
final

'Sample message Notice punctuations'

In [19]:
def text_process(mess):
    nopunc = [c for c in mess if c not in string.punctuation]
    nopunc = ''.join(nopunc)
    return[word for word in nopunc.split() if word.lower() not in stopwords.words('english')]

In [20]:
text_process(mess)

['Sample', 'message', 'Notice', 'punctuations']

In [21]:
test = 'fan % of office & Table are @near'

In [22]:
test

'fan % of office & Table are @near'

In [23]:
text_process(test)

['fan', 'office', 'Table', 'near']

In [24]:
message['message'].head(5)

0    Go until jurong point, crazy.. Available only ...
1                        Ok lar... Joking wif u oni...
2    Free entry in 2 a wkly comp to win FA Cup fina...
3    U dun say so early hor... U c already then say...
4    Nah I don't think he goes to usf, he lives aro...
Name: message, dtype: object

In [25]:
message['message'].head(5).apply(text_process)

0    [Go, jurong, point, crazy, Available, bugis, n...
1                       [Ok, lar, Joking, wif, u, oni]
2    [Free, entry, 2, wkly, comp, win, FA, Cup, fin...
3        [U, dun, say, early, hor, U, c, already, say]
4    [Nah, dont, think, goes, usf, lives, around, t...
Name: message, dtype: object

In [26]:
from sklearn.feature_extraction.text import CountVectorizer
#BOW

In [27]:
bow_transformer = CountVectorizer(analyzer=text_process).fit(message['message'])

In [28]:
mess4 = message['message'][3]
mess4

'U dun say so early hor... U c already then say...'

In [29]:
bow4 = bow_transformer.transform([mess4])

In [30]:
bow4

<1x11396 sparse matrix of type '<class 'numpy.int64'>'
	with 7 stored elements in Compressed Sparse Row format>

In [31]:
bow4.toarray()

array([[0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [32]:
message_bow = bow_transformer.transform(message['message'])

In [33]:
message_bow

<5572x11396 sparse matrix of type '<class 'numpy.int64'>'
	with 50529 stored elements in Compressed Sparse Row format>

In [34]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf_transformer = TfidfTransformer().fit(message_bow)

In [35]:
tfidf4 = tfidf_transformer.transform(bow4)

In [36]:
tfidf4.toarray()

array([[0., 0., 0., ..., 0., 0., 0.]])

In [37]:
message_tfidf = tfidf_transformer.transform(message_bow)

In [38]:
message_tfidf.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [39]:
from sklearn.model_selection import train_test_split
msg_train,msg_test,label_train,label_test = train_test_split(message['message'],message['label'],test_size=0.3)

In [40]:
msg_train

4139    Good! No, don‘t need any receipts—well done! (...
1627                            Dear how you. Are you ok?
4058                      Noice. Text me when you're here
5444    Good morning. At the repair shop--the ONLY rea...
2879    Hey Boys. Want hot XXX pics sent direct 2 ur p...
                              ...                        
5224    OH FUCK. JUSWOKE UP IN A BED ON A BOATIN THE D...
2439        I not busy juz dun wan 2 go so early.. Hee.. 
4776    So many people seems to be special at first si...
902           How is it possible to teach you. And where.
2466                       S.i think he is waste for rr..
Name: message, Length: 3900, dtype: object

In [41]:
label_train

4139     ham
1627     ham
4058     ham
5444     ham
2879    spam
        ... 
5224     ham
2439     ham
4776     ham
902      ham
2466     ham
Name: label, Length: 3900, dtype: object

In [42]:
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier

In [43]:
pipeline = Pipeline([
    ('bow',CountVectorizer(analyzer=text_process)),
    ('tfidf',TfidfTransformer()),
    ('classifier',RandomForestClassifier(n_estimators=10))
    ])

In [44]:
pipeline

Pipeline(steps=[('bow',
                 CountVectorizer(analyzer=<function text_process at 0x00000261835411E0>)),
                ('tfidf', TfidfTransformer()),
                ('classifier', RandomForestClassifier(n_estimators=10))])

In [45]:
pipeline.fit(msg_train,label_train)

Pipeline(steps=[('bow',
                 CountVectorizer(analyzer=<function text_process at 0x00000261835411E0>)),
                ('tfidf', TfidfTransformer()),
                ('classifier', RandomForestClassifier(n_estimators=10))])

In [46]:
predictions = pipeline.predict(msg_test)

In [47]:
predictions

array(['ham', 'ham', 'ham', ..., 'spam', 'spam', 'ham'], dtype=object)

In [48]:
label_test

2418     ham
3747     ham
2294     ham
803     spam
3279     ham
        ... 
1441     ham
716      ham
3334    spam
11      spam
3539     ham
Name: label, Length: 1672, dtype: object

In [49]:
from sklearn.metrics import confusion_matrix,classification_report

In [50]:
print(confusion_matrix(label_test,predictions))

[[1447    1]
 [  54  170]]


In [51]:
print(classification_report(label_test,predictions))

              precision    recall  f1-score   support

         ham       0.96      1.00      0.98      1448
        spam       0.99      0.76      0.86       224

    accuracy                           0.97      1672
   macro avg       0.98      0.88      0.92      1672
weighted avg       0.97      0.97      0.97      1672

